#! /usr/bin/python
import os, pickle

import uvicorn

from visiomatic import package
from visiomatic.server.settings import Settings

def start_server(
        app="src.visiomatic.server.app:create_app",
        host="localhost",
        port=8009,
        root_path="",
        workers=4,
        access_log=False,
        reload=True
    ):
    uvicorn.run(
        app,
        host=host,
        port=port,
        root_path=root_path,
        access_log=access_log,
        workers=workers,
        reload=reload,
        factory=True
    )
    return

if __name__ == "__main__":

    print(f"{package.title} v{package.version}")

    # Set up settings
    settings = Settings()

    '''
    start_server(
        host=args["host"],
        port=args["port"],
        root_path=args["root_path"],
        access_log=args["access_log"],
        reload=args["reload"],
        workers=args["workers"]
    )
    '''
