#! /usr/bin/python
import os, pickle

import uvicorn
from UltraDict import UltraDict

from visiomatic import package
from visiomatic.server.settings import settings

def start_server(
        app="src.visiomatic.server.app:create_app",
        host="localhost",
        port=8009,
        root_path="",
        workers=4,
        access_log=False,
        reload=True
    ):
    uvicorn.run(
        app,
        host=host,
        port=port,
        root_path=root_path,
        access_log=access_log,
        workers=workers,
        reload=reload,
        factory=True
    )
    return

if __name__ == "__main__":

    print(f"{package.title} v{package.version}")

    start_server(
        host=settings["host"],
        port=settings["port"],
        root_path=settings["root_path"],
        access_log=settings["access_log"],
        reload=settings["reload"],
        workers=settings["workers"]
    )

